import { Router} from "express";
import { verifyjwt } from "../middleware/auth.middleware";
import { signUp,gsignUp,logoutUser,getUser,login,glogin,} from "../controllers/user.controller.js";
const router = Router();
router.route("/signup").post(signUp);
router.route("/gsignup").post(gsignUp);
router.post('/login',verifyjwt, login);
router.post('/glogin',verifyjwt, glogin);
router.post('/logout',verifyjwt,logoutUser);
router.get('/getuser', verifyjwt, getUser);
export default router;